[package]
name = "malware_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "*"
egui = "*"
eframe = "*"
write = "*"
wmi = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
num_cpus = "*"
winapi = { version = "*", features = ["winuser"] }
rayon = "*"
criterion = "*"
sha2 = "*"